import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import { streamText } from "ai";
import { createAnthropic } from "@ai-sdk/anthropic";
import { createOpenAI } from "@ai-sdk/openai";
import { getConfig } from "@/lib/config";
import {
  readMarkdown,
  readJson,
  writeMarkdown,
  writeJson,
  exists,
  listFiles,
  updateArticleTitle,
} from "@/lib/data";
import { buildPrompt } from "@/lib/prompt-builder";
import { GenerateInputSchema } from "@/types";
import type { ArticleMeta, ArticleTree } from "@/types";

const MAX_MAIN_VERSIONS = 5;

function getModel(provider: string, model: string) {
  if (provider === "anthropic") {
    return createAnthropic()(model);
  }
  if (provider === "openai") {
    return createOpenAI()(model);
  }
  throw new Error(`Unknown provider: ${provider}`);
}

function buildMockArticle(params: {
  slug: string;
  nodeName: string;
  language: string;
  instruction: string;
  source: string;
}): string {
  const { slug, nodeName, language, instruction, source } = params;
  const sourcePreview = source.slice(0, 220).replace(/\s+/g, " ").trim();

  return [
    `# Mock Draft ${nodeName}`,
    "",
    `This is a deterministic mock output for article "${slug}".`,
    `Language: ${language}`,
    "",
    "## Instruction",
    instruction,
    "",
    "## Source Preview",
    sourcePreview || "(empty source)",
    "",
    "## Mock Body",
    "Paragraph 1: This draft is generated by the mock provider for development and UI testing.",
    "Paragraph 2: It helps verify streaming flow, version creation, persistence, and rendering without external API keys.",
  ].join("\n");
}

function createMockStreamResponse(
  text: string,
  onComplete: () => Promise<void>,
): Response {
  const encoder = new TextEncoder();
  let cancelled = false;
  const chunkSize = 24;
  const chunkDelayMs = 100;

  const stream = new ReadableStream<Uint8Array>({
    async start(controller) {
      try {
        for (let index = 0; index < text.length; index += chunkSize) {
          if (cancelled) return;
          const chunk = text.slice(index, index + chunkSize);
          controller.enqueue(encoder.encode(chunk));
          await new Promise((resolve) => setTimeout(resolve, chunkDelayMs));
        }
        if (!cancelled) {
          await onComplete();
          controller.close();
        }
      } catch (error) {
        controller.error(error);
      }
    },
    cancel() {
      // If the client cancels early, skip persistence to avoid partial writes.
      cancelled = true;
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-cache",
    },
  });
}

function nextNodeName(tree: ArticleTree): string {
  const existing = Object.keys(tree.nodes)
    .filter((n) => /^v\d+$/.test(n))
    .map((n) => parseInt(n.slice(1), 10));
  const max = existing.length > 0 ? Math.max(...existing) : 0;
  return `v${max + 1}`;
}

function isMainVersionNode(nodeName: string): boolean {
  return /^v\d+$/.test(nodeName);
}

function getVersionNumber(nodeName: string): number {
  return parseInt(nodeName.slice(1), 10);
}

function collectPrunableNodes(
  tree: ArticleTree,
  maxMainVersionsToKeep: number,
): string[] {
  const mainVersions = Object.keys(tree.nodes)
    .filter(isMainVersionNode)
    .sort((a, b) => getVersionNumber(a) - getVersionNumber(b));

  if (mainVersions.length <= maxMainVersionsToKeep) {
    return [];
  }

  const overflowMainVersions = mainVersions.slice(
    0,
    mainVersions.length - maxMainVersionsToKeep,
  );
  const toPrune = new Set<string>(overflowMainVersions);
  const stack = [...overflowMainVersions];

  while (stack.length > 0) {
    const nodeName = stack.pop();
    if (!nodeName) continue;
    const node = tree.nodes[nodeName];
    if (!node) continue;

    for (const child of node.children) {
      if (!toPrune.has(child)) {
        toPrune.add(child);
        stack.push(child);
      }
    }
  }

  return [...toPrune];
}

function pruneTree(
  tree: ArticleTree,
  prunedNodeNames: Set<string>,
): ArticleTree {
  const nextNodes: ArticleTree["nodes"] = {};

  for (const [nodeName, node] of Object.entries(tree.nodes)) {
    if (prunedNodeNames.has(nodeName)) continue;

    nextNodes[nodeName] = {
      ...node,
      children: node.children.filter((child) => !prunedNodeNames.has(child)),
    };
  }

  const remainingMainVersions = Object.keys(nextNodes)
    .filter(isMainVersionNode)
    .sort((a, b) => getVersionNumber(a) - getVersionNumber(b));

  return {
    rootNode:
      tree.rootNode && !prunedNodeNames.has(tree.rootNode)
        ? tree.rootNode
        : (remainingMainVersions[0] ?? null),
    bestNode:
      tree.bestNode && !prunedNodeNames.has(tree.bestNode)
        ? tree.bestNode
        : null,
    latestNode:
      tree.latestNode && !prunedNodeNames.has(tree.latestNode)
        ? tree.latestNode
        : (remainingMainVersions[remainingMainVersions.length - 1] ?? null),
    nodes: nextNodes,
  };
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ slug: string }> },
) {
  const { slug } = await params;

  const articleExists = await exists(`articles/${slug}/meta.json`);
  if (!articleExists) {
    return NextResponse.json({ error: "Article not found" }, { status: 404 });
  }

  let body: unknown;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
  }

  const parsed = GenerateInputSchema.safeParse(body);
  if (!parsed.success) {
    return NextResponse.json(
      { error: "Missing or invalid instruction" },
      { status: 400 },
    );
  }

  const { instruction, source } = parsed.data;

  if (source !== undefined) {
    await writeMarkdown(`articles/${slug}/source.md`, {}, source);
  }

  const meta = await readJson<ArticleMeta>(`articles/${slug}/meta.json`);
  const tree = await readJson<ArticleTree>(`articles/${slug}/tree.json`);

  // Keep one slot for the incoming main version: delete old versions first, then generate.
  const prePrunableNodeNames = collectPrunableNodes(
    tree,
    MAX_MAIN_VERSIONS - 1,
  );
  const prePrunableSet = new Set(prePrunableNodeNames);
  const treeBeforeGenerate = pruneTree(tree, prePrunableSet);

  await Promise.allSettled(
    prePrunableNodeNames.flatMap((name) => [
      fs.rm(`data/articles/${slug}/nodes/${name}.md`, { force: true }),
      fs.rm(`data/articles/${slug}/evaluation/${name}.json`, { force: true }),
    ]),
  );

  const nodeName = nextNodeName(treeBeforeGenerate);

  const config = await getConfig();
  const referenceGroupName = meta.styleRef ?? "default";
  const { content: profileContent } = await readMarkdown("profiles/default.md");

  const references: string[] = [];
  const refFileNames: string[] = [];
  try {
    const refFiles = await listFiles(`references/${referenceGroupName}`, ".md");
    for (const f of refFiles.sort()) {
      const { content } = await readMarkdown(
        `references/${referenceGroupName}/${f}`,
      );
      references.push(content);
      refFileNames.push(f);
    }
  } catch {
    // no reference directory
  }

  let commonInstruction = "";
  try {
    const { content } = await readMarkdown("instruction/instruction.md");
    commonInstruction = content;
  } catch {
    // no instruction file
  }

  let outputRules = "";
  try {
    const { content } = await readMarkdown("instruction/output-rules.md");
    outputRules = content;
  } catch {
    // no output rules file
  }

  const { content: sourceContent } = await readMarkdown(
    `articles/${slug}/source.md`,
  );

  const { systemPrompt, userMessage } = buildPrompt({
    profile: profileContent,
    references,
    commonInstruction,
    outputRules,
    source: sourceContent,
    instruction,
  });

  console.log(
    [
      `[generate] ${slug}`,
      `[profile] ${profileContent}`,
      `[referenceGroup] ${referenceGroupName}`,
      `[refs] [${refFileNames.join(", ")}]`,
      `[commonInstruction] ${commonInstruction}`,
      `[outputRules] ${outputRules}`,
      `[userInstruction] ${instruction}`,
    ].join("\n"),
  );

  async function persistGeneratedNode(text: string): Promise<void> {
    await writeMarkdown(
      `articles/${slug}/nodes/${nodeName}.md`,
      {
        node: nodeName,
        generatedAt: new Date().toISOString(),
        instruction,
      },
      text,
    );

    const updatedTree: ArticleTree = {
      rootNode: treeBeforeGenerate.rootNode || nodeName,
      bestNode: treeBeforeGenerate.bestNode,
      latestNode: nodeName,
      nodes: {
        ...treeBeforeGenerate.nodes,
        [nodeName]: { parent: null, depth: 1, children: [] },
      },
    };
    await writeJson(`articles/${slug}/tree.json`, updatedTree);
    await updateArticleTitle(slug, text);
  }

  if (config.models.writing.provider === "mock") {
    const mockText = buildMockArticle({
      slug,
      nodeName,
      language: config.language,
      instruction,
      source: sourceContent,
    });
    return createMockStreamResponse(mockText, () =>
      persistGeneratedNode(mockText),
    );
  }

  const model = getModel(
    config.models.writing.provider,
    config.models.writing.model,
  );

  const result = streamText({
    model,
    system: systemPrompt,
    messages: [{ role: "user", content: userMessage }],
    async onFinish({ text, usage }) {
      console.log(
        `[generate] ${slug}/${nodeName} | tokens: ${usage.inputTokens} in + ${usage.outputTokens} out`,
      );
      await persistGeneratedNode(text);
    },
  });

  return result.toTextStreamResponse();
}
